{ ... }:
{
  enable = true;
  configFile = ''
    ;; zile configuration generated by home-manager
    (setq inhibit-splash-screen t)
    (setq kill-whole-line t)
    (setq ring-bell nil)
    (setq backup-directory "~/.backups")
  '';
}
