{autostart, ...}: let
  gaps = {
    inner = "10";
    outer = "10";
  };
  mods = rec {
    primary = "alt-cmd-ctrl";
    secondary = "${primary}-shift";
  };
  loginStart =
    if autostart
    then "true"
    else "false";
in ''  # Generated by nix
  # You can use it to add commands that run after login to macOS user session.
  # 'start-at-login' needs to be 'true' for 'after-login-command' to work
  # Available commands: https://nikitabobko.github.io/AeroSpace/commands
  after-login-command = []

  # You can use it to add commands that run after AeroSpace startup.
  # 'after-startup-command' is run after 'after-login-command'
  # Available commands : https://nikitabobko.github.io/AeroSpace/commands
  after-startup-command = [
    'exec-and-forget /opt/homebrew/bin/borders active_color=0xffe2e2e3 inactive_color=0xff414550 width=6.0 style=round'
  ]

  # Start AeroSpace at login
  start-at-login = ${loginStart}

  # Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
  enable-normalization-flatten-containers = true
  enable-normalization-opposite-orientation-for-nested-containers = true

  # See: https://nikitabobko.github.io/AeroSpace/guide#layouts
  # The 'accordion-padding' specifies the size of accordion padding
  # You can set 0 to disable the padding feature
  accordion-padding = 30

  # Possible values: tiles|accordion
  default-root-container-layout = 'tiles'

  # Possible values: horizontal|vertical|auto
  # 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
  #               tall monitor (anything higher than wide) gets vertical orientation
  default-root-container-orientation = 'auto'

  # Possible values: (qwerty|dvorak)
  # See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
  key-mapping.preset = 'qwerty'

  # Mouse follows focus when focused monitor changes
  # Drop it from your config, if you don't like this behavior
  # See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
  # See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
  on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

  # Gaps between windows (inner-*) and between monitor edges (outer-*).
  # Possible values:
  # - Constant:     gaps.outer.top = 8
  # - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
  #                 In this example, 24 is a default value when there is no match.
  #                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
  #                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
  [gaps]
  inner.horizontal = ${gaps.inner}
  inner.vertical =   ${gaps.inner}
  outer.left =       ${gaps.outer}
  outer.bottom =     ${gaps.outer}
  outer.top =        ${gaps.outer}
  outer.right =      ${gaps.outer}

  # 'main' binding mode declaration
  # See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
  # 'main' binding mode must be always presented
  [mode.main.binding]

  # All possible keys:
  # - Letters.        a, b, c, ..., z
  # - Numbers.        0, 1, 2, ..., 9
  # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
  # - F-keys.         f1, f2, ..., f20
  # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
  #                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
  # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
  #                   keypadMinus, keypadMultiply, keypadPlus
  # - Arrows.         left, down, up, right

  # All possible modifiers: cmd, alt, ctrl, shift

  # All possible commands: https://nikitabobko.github.io/AeroSpace/commands

  # See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
  # You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
  # alt-enter = '''exec-and-forget osascript -e '
  # tell application "Terminal"
  #     do script
  #     activate
  # end tell'
  # '''

  # See: https://nikitabobko.github.io/AeroSpace/commands#layout
  ${mods.primary}-slash = 'layout tiles horizontal vertical'
  ${mods.primary}-comma = 'layout accordion horizontal vertical'

  # See: https://nikitabobko.github.io/AeroSpace/commands#focus
  ${mods.primary}-left = 'focus left'
  ${mods.primary}-down = 'focus down'
  ${mods.primary}-up = 'focus up'
  ${mods.primary}-right = 'focus right'

  # See: https://nikitabobko.github.io/AeroSpace/commands#move
  ${mods.secondary}-left = 'move left'
  ${mods.secondary}-down = 'move down'
  ${mods.secondary}-up = 'move up'
  ${mods.secondary}-right = 'move right'

  # See: https://nikitabobko.github.io/AeroSpace/commands#resize
  ${mods.secondary}-minus = 'resize smart -50'
  ${mods.secondary}-equal = 'resize smart +50'

  # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
  ${mods.primary}-1 = 'workspace 1'
  ${mods.primary}-2 = 'workspace 2'
  ${mods.primary}-3 = 'workspace 3'
  ${mods.primary}-4 = 'workspace 4'
  ${mods.primary}-5 = 'workspace 5'
  ${mods.primary}-6 = 'workspace 6'
  ${mods.primary}-7 = 'workspace 7'
  ${mods.primary}-8 = 'workspace 8'
  ${mods.primary}-9 = 'workspace 9'
  ${mods.primary}-b = 'workspace B' # Browser
  ${mods.primary}-c = 'workspace C' # Chat
  ${mods.primary}-e = 'workspace E' # Editor
  ${mods.primary}-m = 'workspace M' # Music
  ${mods.primary}-n = 'workspace N' # Notes
  ${mods.primary}-p = 'workspace P' # Personal
  ${mods.primary}-t = 'workspace T' # Terminal

  # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
  ${mods.secondary}-1 = 'move-node-to-workspace 1'
  ${mods.secondary}-2 = 'move-node-to-workspace 2'
  ${mods.secondary}-3 = 'move-node-to-workspace 3'
  ${mods.secondary}-4 = 'move-node-to-workspace 4'
  ${mods.secondary}-5 = 'move-node-to-workspace 5'
  ${mods.secondary}-6 = 'move-node-to-workspace 6'
  ${mods.secondary}-7 = 'move-node-to-workspace 7'
  ${mods.secondary}-8 = 'move-node-to-workspace 8'
  ${mods.secondary}-9 = 'move-node-to-workspace 9'
  ${mods.secondary}-b = 'move-node-to-workspace B' # Browser
  ${mods.secondary}-c = 'move-node-to-workspace C' # Chat
  ${mods.secondary}-e = 'move-node-to-workspace E' # Editor
  ${mods.secondary}-m = 'move-node-to-workspace M' # Music
  ${mods.secondary}-n = 'move-node-to-workspace N' # Notes
  ${mods.secondary}-p = 'move-node-to-workspace P' # Personal
  ${mods.secondary}-t = 'move-node-to-workspace T' # Terminal

  # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
  ${mods.primary}-tab = 'workspace-back-and-forth'
  # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
  ${mods.secondary}-tab = 'move-workspace-to-monitor --wrap-around next'

  # See: https://nikitabobko.github.io/AeroSpace/commands#mode
  ${mods.secondary}-semicolon = 'mode service'

  # 'service' binding mode declaration.
  # See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
  [mode.service.binding]
  esc = ['reload-config', 'mode main']
  r = ['flatten-workspace-tree', 'mode main'] # reset layout
  #s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
  f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
  backspace = ['close-all-windows-but-current', 'mode main']

  ${mods.secondary}-left = ['join-with left', 'mode main']
  ${mods.secondary}-down = ['join-with down', 'mode main']
  ${mods.secondary}-up = ['join-with up', 'mode main']
  ${mods.secondary}-right = ['join-with right', 'mode main']

  [workspace-to-monitor-force-assignment]
  B = 'main'     # Browser
  C = 'built-in' # Chat
  E = 'main'     # Editor
  M = 'main'     # Music
  N = 'built-in' # Notes
  P = 'main'     # Personal
  T = 'built-in' # Terminal

  [[on-window-detected]]
  if.app-id = 'com.github.wez.wezterm'
  run = ['layout tiling', 'move-node-to-workspace T']

  [[on-window-detected]]
  if.app-id = 'com.googlecode.iterm2'
  run = ['layout tiling', 'move-node-to-workspace T']

  [[on-window-detected]]
  if.app-id = 'com.google.Chrome'
  if.workspace = 'P'
  run = ['layout tiling', 'move-node-to-workspace P']

  [[on-window-detected]]
  if.app-id = 'com.google.Chrome'
  if.workspace = 'B'
  run = ['layout tiling', 'move-node-to-workspace B']

  [[on-window-detected]]
  if.app-id = 'com.google.Chrome'
  if.window-title-regex-substring = '.*\(Main\)$'
  run = ['layout tiling', 'move-node-to-workspace P']

  [[on-window-detected]]
  if.app-id = 'com.google.Chrome'
  if.window-title-regex-substring = '.*\(Google\)$'
  run = ['layout tiling', 'move-node-to-workspace B']

  [[on-window-detected]]
  if.app-name-regex-substring = 'Cursor'
  run = ['layout tiling', 'move-node-to-workspace E']

  [[on-window-detected]]
  if.app-id = 'com.microsoft.VSCode'
  run = ['layout tiling', 'move-node-to-workspace E']

  [[on-window-detected]]
  if.app-id = 'org.gnu.Emacs'
  run = ['layout tiling', 'move-node-to-workspace E']

  [[on-window-detected]]
  if.app-id = 'notion.id'
  run = ['layout tiling', 'move-node-to-workspace N']

  [[on-window-detected]]
  if.app-name-regex-substring = 'Slack'
  run = ['layout tiling', 'move-node-to-workspace C']

  [[on-window-detected]]
  if.app-id = 'com.spotify.client'
  run = ['layout tiling', 'move-node-to-workspace M']

  [[on-window-detected]]
  if.app-id = 'com.apple.systempreferences'
  run = ['layout floating']

''
