# This module applies only starting with Sonoma (14.5)
{
  config,
  lib,
  ...
}:
with lib; let
  cfg = config.security.pam.sudo_local;
  compareTo = config.versions.darwin.compareTo;
in {
  options.security.pam.sudo_local = {
    entries = mkOption {
      type = types.listOf (types.submodule {
        options = {
          type = mkOption {
            type = types.enum ["auth" "account" "password" "session"];
            default = "auth";
          };
          control = mkOption {
            type = types.enum ["required" "requisite" "sufficient" "optional" "include" "substack"];
            default = "optional";
          };
          module = mkOption {
            type = types.str;
          };
          arguments = mkOption {
            type = types.listOf types.str;
            default = [];
          };
          comment = mkOption {
            type = types.str;
            default = "security.pam.sudo_local";
          };
        };
      });
    };
  };

  config = {
    assertions = [
      {
        assertion = compareTo "14.5" >= 0;
        message = "security.pam.sudo_local requires MacOS Sonoma (14.5)";
      }
    ];

    environment.etc."pam.d/sudo_local".text = let
      formatEntry = entry:
        lib.concatStringsSep "\t" [
          entry.type
          entry.control
          entry.module
          (concatStringsSep " " entry.arguments)
          "# nix-darwin: ${entry.comment}"
        ];
      lines =
        [
          "# Generated by nix-darwin sudo_local module"
        ]
        ++ (builtins.map formatEntry cfg.entries);
    in
      lib.concatStringsSep "\n" lines;
  };
}
