name: CI - Darwin Configurations

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-darwin:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - spectre
          - ash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-platforms = aarch64-darwin x86_64-darwin

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build Darwin configuration
        run: |
          nix build \
            --no-link \
            --print-build-logs \
            --show-trace \
            .#darwinConfigurations.${{ matrix.configuration }}.system
