name: CI - Linux Configurations

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-nixos:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - devbox

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build NixOS configuration
        run: |
          nix build \
            --no-link \
            --print-build-logs \
            --show-trace \
            .#nixosConfigurations.${{ matrix.configuration }}.config.system.build.toplevel
